
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzhldhivkhhqgjdslini.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6aGxkaGl2a2hocWdqZHNsaW5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NTI3MTEsImV4cCI6MjA2MjUyODcxMX0.bcmxz-tqN4P_t7_ybUn5jyrSKxttuV0SMzFIq-ti_2c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
